apiVersion: v1
kind: Pod
metadata:
  name: badpod03
spec:
  containers:
  - name: container01
    image: busybox
    securityContext:
      capabilities:
        add:
        - NET_RAW  # Disallowed capability
  - name: container02
    image: busybox
    securityContext:
      capabilities:
        add:
        - SETGID   # Allowed capability