apiVersion: v1
kind: Pod
metadata:
  name: attackpod
spec:
  containers:
  - name: attacker
    image: busybox
    securityContext:
      capabilities:
        add:
        - NET_RAW  # Disallowed in secure policies
    command: ["sh", "-c", "sleep 100000"]
