###### Pods - Bad
---
apiVersion: v1
kind: Pod
metadata:
  name: badpod01
spec:
  containers:
  - name: container01
    image: busybox
    securityContext:
      capabilities:
        add:
        - NET_RAW  # Disallowed capability
---
apiVersion: v1
kind: Pod
metadata:
  name: badpod02
spec:
  containers:
  - name: container01
    image: busybox
    securityContext:
      capabilities:
        add:
        - NET_RAW  # Disallowed capability
        - SETGID   # Allowed capability
---
apiVersion: v1
kind: Pod
metadata:
  name: badpod03
spec:
  containers:
  - name: container01
    image: busybox
    securityContext:
      capabilities:
        add:
        - NET_RAW  # Disallowed capability
  - name: container02
    image: busybox
    securityContext:
      capabilities:
        add:
        - SETGID   # Allowed capability
---
apiVersion: v1
kind: Pod
metadata:
  name: badpod04
spec:
  initContainers:
  - name: initcontainer01
    image: busybox
    securityContext:
      capabilities:
        add:
        - NET_RAW  # Disallowed capability
  containers:
  - name: container01
    image: busybox
    securityContext:
      capabilities:
        add:
        - SETGID   # Allowed capability
---
apiVersion: v1
kind: Pod
metadata:
  name: badpod05
spec:
  initContainers:
  - name: initcontainer01
    image: busybox
  - name: initcontainer02
    image: busybox
    securityContext:
      capabilities:
        add:
        - NET_RAW  # Disallowed capability
  containers:
  - name: container01
    image: busybox
    securityContext:
      capabilities:
        add:
        - SETGID   # Allowed capability
---
apiVersion: v1
kind: Pod
metadata:
  name: badpod06
spec:
  initContainers:
  - name: initcontainer01
    image: busybox
    securityContext:
      capabilities:
        add:
        - NET_RAW  # Disallowed capability
  containers:
  - name: container01
    image: busybox
    securityContext:
      capabilities:
        add:
        - SYS_ADMIN  # Disallowed capability
---
###### Deployments - Bad
apiVersion: apps/v1
kind: Deployment
metadata:
  name: baddeployment01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: container01
        image: busybox
        securityContext:
          capabilities:
            add:
            - NET_RAW  # Disallowed capability
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: baddeployment02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: container01
        image: busybox
        securityContext:
          capabilities:
            add:
            - NET_RAW  # Disallowed capability
            - SETGID   # Allowed capability
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: baddeployment03
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: container01
        image: busybox
        securityContext:
          capabilities:
            add:
            - NET_RAW  # Disallowed capability
      - name: container02
        image: busybox
        securityContext:
          capabilities:
            add:
            - SETGID   # Allowed capability
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: baddeployment04
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      initContainers:
      - name: initcontainer01
        image: busybox
        securityContext:
          capabilities:
            add:
            - NET_RAW  # Disallowed capability
      containers:
      - name: container01
        image: busybox
        securityContext:
          capabilities:
            add:
            - SETGID   # Allowed capability
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: baddeployment05
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      initContainers:
      - name: initcontainer01
        image: busybox
      - name: initcontainer02
        image: busybox
        securityContext:
          capabilities:
            add:
            - NET_RAW  # Disallowed capability
      containers:
      - name: container01
        image: busybox
        securityContext:
          capabilities:
            add:
            - SETGID   # Allowed capability
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: baddeployment06
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      initContainers:
      - name: initcontainer01
        image: busybox
        securityContext:
          capabilities:
            add:
            - NET_RAW  # Disallowed capability
      containers:
      - name: container01
        image: busybox
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN  # Disallowed capability
---
###### CronJobs - Bad
apiVersion: batch/v1
kind: CronJob
metadata:
  name: badcronjob01
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: container01
            image: busybox
            securityContext:
              capabilities:
                add:
                - NET_RAW  # Disallowed capability
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: badcronjob02
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: container01
            image: busybox
            securityContext:
              capabilities:
                add:
                - NET_RAW  # Disallowed capability
                - SETGID   # Allowed capability
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: badcronjob03
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: container01
            image: busybox
            securityContext:
              capabilities:
                add:
                - NET_RAW  # Disallowed capability
          - name: container02
            image: busybox
            securityContext:
              capabilities:
                add:
                - SETGID   # Allowed capability
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: badcronjob04
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          initContainers:
          - name: initcontainer01
            image: busybox
            securityContext:
              capabilities:
                add:
                - NET_RAW  # Disallowed capability
          containers:
          - name: container01
            image: busybox
            securityContext:
              capabilities:
                add:
                - SETGID   # Allowed capability
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: badcronjob05
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          initContainers:
          - name: initcontainer01
            image: busybox
          - name: initcontainer02
            image: busybox
            securityContext:
              capabilities:
                add:
                - NET_RAW  # Disallowed capability
          containers:
          - name: container01
            image: busybox
            securityContext:
              capabilities:
                add:
                - SETGID   # Allowed capability
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: badcronjob06
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          initContainers:
          - name: initcontainer01
            image: busybox
            securityContext:
              capabilities:
                add:
                - NET_RAW  # Disallowed capability
          containers:
          - name: container01
            image: busybox
            securityContext:
              capabilities:
                add:
                - SYS_ADMIN  # Disallowed capability
