apiVersion: v1
kind: Pod
metadata:
  name: badpod05
spec:
  containers:
  - name: container01
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    ports:
    - name: web-secure
      containerPort: 4443
      hostPort: 443
  - name: container02
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    ports:
    - name: dns
      containerPort: 5553
      hostPort: 53
      protocol: UDP
