apiVersion: v1
kind: Pod
metadata:
  name: badpod01
spec:
  containers:
  - name: container01
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    ports:
    - name: dns
      containerPort: 5553
      hostPort: 53
