apiVersion: v1
kind: Pod
metadata:
  name: badpod04
spec:
  containers:
  - name: container01
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    ports:
    - name: admin
      containerPort: 8000
      protocol: TCP
  - name: container02
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    ports:
    - name: dns
      containerPort: 5553
      hostPort: 53
      protocol: UDP
